### ISSUE TITLE
Getting a weird (and random) error with the cryptography libary

### ISSUE THREAD

**Issue by sarthakpati** [intel/openfl#1015]
**Describe the bug**
The following error is observed intermetently during the GaNDLF-OpenFL workflow runs [[ref](https://github.com/mlcommons/GaNDLF/actions/runs/10146156611/job/28053555807?pr=845)]:

```python-traceback
✔️ OK
[14:27:19] INFO     FL-Plan hash is 87330787581a0681932044e46d4513adc0d483087e4524f0f1d25570affbd87e3d0d3011df48c3434d74e55030ea02d5                 plan.py:250
           INFO     plan.yaml frozen successfully                                                                                                     plan.py:58

 🗜️ Preparing workspace distribution zip file

 ✔️ Workspace exported to archive: aggregator.zip

 ✔️ OK
Creating AGGREGATOR certificate key pair with following settings: CN=fv-az1245-288.44uquw3knzoenloncamig1c14h.dx.internal.cloudapp.net, SAN=DNS:fv-az1245-288.44uquw3knzoenloncamig1c14h.dx.internal.cloudapp.net
Traceback (most recent call last):
EXCEPTION : Attribute's length must be >= 1 and <= 64, but it was 65
  File "/opt/hostedtoolcache/Python/3.9.19/x64/bin/fx", line 8, in <module>
    sys.exit(entry())
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/interface/cli.py", line 268, in entry
    error_handler(e)
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/interface/cli.py", line 195, in error_handler
    raise error
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/interface/cli.py", line 266, in entry
    cli(max_content_width=120)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/click/core.py", line [783](https://github.com/mlcommons/GaNDLF/actions/runs/10146156611/job/28053555807?pr=845#step:10:784), in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/interface/aggregator.py", line 86, in _generate_cert_request
    generate_cert_request(fqdn)
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/interface/aggregator.py", line 105, in generate_cert_request
    server_private_key, server_csr = generate_csr(common_name, server=True)
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/cryptography/participant.py", line 29, in generate_csr
    x509.NameAttribute(NameOID.COMMON_NAME, common_name),
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/cryptography/x509/name.py", line 152, in __init__
    raise ValueError(msg)
ValueError: Attribute's length must be >= 1 and <= 64, but it was 65
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/tests/github/test_gandlf.py", line 76, in <module>
    certify_aggregator(fqdn)
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/tests/github/utils.py", line 77, in certify_aggregator
    check_call(['fx', 'aggregator', 'generate-cert-request', '--fqdn', fqdn])
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['fx', 'aggregator', 'generate-cert-request', '--fqdn', 'fv-az1245-288.44uquw3knzoenloncamig1c14h.dx.internal.cloudapp.net']' returned non-zero exit status 1.
```

**To Reproduce**
N.A.

**Expected behavior**
This should be detected earlier on or perhaps not even hit upon, since re-running the workflow (usually) makes it go away.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
N.A.

**Smartphone (please complete the following information):**
N.A.

**Additional context**
N.A.

**Comment by psfoley** [comment]
Thanks for reporting, @sarthakpati! @MasterSkepticista I think this may be due to the issue you reported about the longer Github Actions VM FQDN length causing problems

**Comment by MasterSkepticista** [comment]
Will be fixed in #1012.

**Comment by sarthakpati** [comment]
Hi,

We are seeing this with [another PR](https://github.com/mlcommons/GaNDLF/pull/916), but it is persistent (2 failures in the last 12 hours): https://github.com/mlcommons/GaNDLF/actions/workflows/openfl-test.yml

Anything we can do to circumvent this?

**Comment by sarthakpati** [comment]
Hey @psfoley @MasterSkepticista - is there any timeline for this fix to be available as a tag? All GaNDLF PRs are having issues because of this: https://github.com/mlcommons/GaNDLF/actions/workflows/openfl-test.yml

**Comment by psfoley** [comment]
Hi @sarthakpati - we tracked this down to be a Github Actions issue - they made a change internally so the FQDN of the environment where they run the job is randomly generated and can sometimes exceed 64 characters. I've submitted a PR to GaNDLF to use the FQDN of `localhost` to avoid this problem in the future https://github.com/mlcommons/GaNDLF/pull/934.

**Comment by sarthakpati** [comment]
Thank you so much!
