### ISSUE TITLE
Bug while creating local CA with https server

### ISSUE THREAD

**Issue by alexey-khorkin** [intel/openfl#163]
Bug while creating CA:

`fx pki install -p </path/to/ca/dir> --ca-url <host:port>`

Got an exception:

```
Password: 
Repeat for confirmation: 
[16:23:46] INFO     Creating CA                                                                                                                        ca.py:157
CA binaries from github will be downloaded now [Y/n]: y
[16:23:51] INFO     Downloading step-ca_linux_0.17.2_amd64.tar.gz.sig                                                                                   ca.py:57
EXCEPTION : Unknown archive format './step-ca_linux_0.17.2_amd64.tar.gz.sig'
Traceback (most recent call last):
...
  File "/home/akhorkin/.virtualenvs/openfl/bin/fx", line 8, in <module>
    sys.exit(entry())
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/interface/cli.py", line 214, in entry
    error_handler(e)
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/interface/cli.py", line 173, in error_handler
    raise error
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/interface/cli.py", line 212, in entry
    cli()
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/interface/pki.py", line 64, in install_
    install(ca_path, ca_url, password)
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/component/ca/ca.py", line 168, in install
    download_step_bin(url, 'step-ca_linux', 'amd', prefix=ca_path, confirmation=False)
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/component/ca/ca.py", line 59, in download_step_bin
    shutil.unpack_archive(f'{prefix}/{name}', f'{prefix}/step')
  File "/usr/local/lib/python3.8/shutil.py", line 1223, in unpack_archive
    raise ReadError("Unknown archive format '{0}'".format(filename))
shutil.ReadError: Unknown archive format './step-ca_linux_0.17.2_amd64.tar.gz.sig'
```

**Desktop:**
 - OS: Ubuntu 18.04.5 LTS
 - Python: Python 3.8.5

Expected behavior:
- Need to download and unpack `.zip` archive

**Comment by psfoley** [comment]
Closing with merge of https://github.com/intel/openfl/pull/164
