### ISSUE TITLE
Run envoys from one folder

### ISSUE THREAD

**Issue by alexey-khorkin** [intel/openfl#193]
1. git checkout one_folder_issue
2. Go to `TensorMNIST` folder:
 ```
cd openfl-tutorials/interactive_api/TensorMNIST/
```
3. Start director:
Go to the `director_folder` and then:
```
./start_director.sh
```
4. Start envoys:
Go to `envoy_one_folder`
```
./start_envoy_one.sh
```
From another terminal:
```
./start_envoy_two.sh
```
5. Run `Mnist_Classification_FL.ipynb` notebook (run all cells)
6. Now you might faced with the issue, but if not:
      6.1) In jupyter notebook: rename `experiment_name` string variable to another
      6.2) Run this cell
      6.3) Run experiment (run the last cell)

7. See the issue from one of envoy:
```
           ERROR    Collaborator failed with error: [Errno 39] Directory not empty: '/home/akhorkin/Repositories/alexey-khorkin-repos/openfl/openfl- envoy.py:69
                    tutorials/interactive_api/Tensorflow_MNIST/envoy_one_folder/mnist_experiment2':                                                             
                    Traceback (most recent call last):                                                                                                          
                      File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 64, in run                    
                        with ExperimentWorkspace(                                                                                                               
                      File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/utilities/workspace.py", line 58, in __enter__                
                        shutil.rmtree(self.experiment_work_dir)                                                                                                 
                      File "/usr/local/lib/python3.8/shutil.py", line 719, in rmtree                                                                            
                        onerror(os.rmdir, path, sys.exc_info())                                                                                                 
                      File "/usr/local/lib/python3.8/shutil.py", line 717, in rmtree                                                                            
                        os.rmdir(path)                                                                                                                          
                    OSError: [Errno 39] Directory not empty: '/home/akhorkin/Repositories/alexey-khorkin-repos/openfl/openfl-tutorials/interactive_a            
                    pi/Tensorflow_MNIST/envoy_one_folder/mnist_experiment2'                                                                                     
           INFO     Send WaitExperiment request                                                                                            director_client.py:70
           INFO     WaitExperiment response has received                                                                                   director_client.py:72
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Python 3.8.5

**Comment by alexey-khorkin** [comment]
I think, this issue could be closed according to https://github.com/intel/openfl/pull/367#pullrequestreview-904883101
