### ISSUE TITLE
Circular import issue

### ISSUE THREAD

**Issue by alexey-khorkin** [intel/openfl#198]
If we import `Director` class in `openfl/transport/grpc/director_server.py` (for type annotation or just not to use `director_cls` parameter in `DirectorGRPCServer` initialization func) we will see ImportError.

1. git checkout circular_imports_issue
2. pip install .
3. fx director start --disable-tls -c openfl-tutorials/interactive_api/Tensorflow_MNIST/director_folder/director_config.yaml
```
Traceback (most recent call last):
  File "/home/akhorkin/.virtualenvs/openfl/bin/fx", line 8, in <module>
    sys.exit(entry())
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/interface/cli.py", line 207, in entry
    command_group = import_module(module, package)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/interface/director.py", line 17, in <module>
    from openfl.component.director import Director
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/component/director/__init__.py", line 6, in <module>
    from .director import Director
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/component/director/director.py", line 13, in <module>
    from openfl.federated import Plan
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/federated/__init__.py", line 7, in <module>
    from .plan import Plan  # NOQA
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/federated/plan/__init__.py", line 6, in <module>
    from .plan import Plan
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 18, in <module>
    from openfl.transport import AggregatorGRPCServer
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/transport/__init__.py", line 6, in <module>
    from .grpc import AggregatorGRPCServer
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/transport/grpc/__init__.py", line 7, in <module>
    from .director_server import DirectorGRPCServer
  File "/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/transport/grpc/director_server.py", line 15, in <module>
    from openfl.component.director import Director
ImportError: cannot import name 'Director' from partially initialized module 'openfl.component.director' (most likely due to a circular import) (/home/akhorkin/.virtualenvs/openfl/lib/python3.8/site-packages/openfl/component/director/__init__.py)
```

I guess it 's a good way to import `Director` for `DirectorGRPCServer` inside `director_server.py`, but now it leads to import error

**Comment by alexey-gruzdev** [comment]
I believe it's not an issue, and should be investigated in the different manner. I am closing this issue, and additional investigation would be raised after #188 would be merged.
