### ISSUE TITLE
pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found

### ISSUE THREAD

**Issue by yjwong1999** [intel/openfl#299]
I encounter these errors when i try to run :fx envoy start" command:
**AttributeError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlInitWithFlags**
**pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found**

- I'm not sure how to resolve the first issue

- For the second error, a github issues says that:
[Unfortunately this tool (as well as any other GPU management tools) depends on the Nvidia driver and toolkit, you should at least install the Nvidia-driver to get things work.](https://github.com/wookayin/gpustat/issues/90#issuecomment-679933017)

My device don't have nvidia graphic cards, how can I solve this?
The detail of the error log is show below.
Many thanks for any advice!

[03:31:56] INFO     🧿 Starting the Envoy.                                                                                                           envoy.py:53
EXCEPTION : Function Not Found
Traceback (most recent call last):
  File "/home/tham/openfl/lib/python3.6/site-packages/pynvml/nvml.py", line 782, in _nvmlGetFunctionPointer
    _nvmlGetFunctionPointer_cache[name] = getattr(nvmlLib, name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1: undefined symbol: nvmlInitWithFlags

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tham/openfl/bin/fx", line 8, in <module>
    sys.exit(entry())
  File "/home/tham/openfl/lib/python3.6/site-packages/openfl/interface/cli.py", line 214, in entry
    error_handler(e)
  File "/home/tham/openfl/lib/python3.6/site-packages/openfl/interface/cli.py", line 173, in error_handler
    raise error
  File "/home/tham/openfl/lib/python3.6/site-packages/openfl/interface/cli.py", line 212, in entry
    cli()
  File "/home/tham/openfl/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/tham/openfl/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/tham/openfl/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tham/openfl/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tham/openfl/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tham/openfl/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/tham/openfl/lib/python3.6/site-packages/openfl/interface/envoy.py", line 82, in start_
    module = import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tham/openfl/lib/python3.6/site-packages/openfl/plugins/processing_units_monitor/pynvml_monitor.py", line 13, in <module>
    pynvml.nvmlInit()
  File "/home/tham/openfl/lib/python3.6/site-packages/pynvml/nvml.py", line 1450, in nvmlInit
    nvmlInitWithFlags(0)
  File "/home/tham/openfl/lib/python3.6/site-packages/pynvml/nvml.py", line 1438, in nvmlInitWithFlags
    fn = _nvmlGetFunctionPointer("nvmlInitWithFlags")
  File "/home/tham/openfl/lib/python3.6/site-packages/pynvml/nvml.py", line 785, in _nvmlGetFunctionPointer
    raise NVMLError(NVML_ERROR_FUNCTION_NOT_FOUND)
pynvml.nvml.NVMLError_FunctionNotFound: Function Not Found

**Comment by alexey-gruzdev** [comment]
@yjwong1999 thanks for reaching us out. 

I believe it's connected with installation and usage of config, which require GPU for training. I believe you can simply disable this from config file and left the field empty. You could double-check difference [here](https://github.com/intel/openfl/blob/develop/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/envoy_config_no_gpu.yaml) and [here](https://github.com/intel/openfl/blob/develop/openfl-tutorials/interactive_api/PyTorch_Kvasir_UNet/envoy/envoy_config.yaml).

**Comment by yjwong1999** [comment]
@alexey-gruzdev 
Thanks for the feedback! I tried and it works!
I remembered to set **cuda_devices** as [], but I forgot to leave the **optional_plugin_component** field empty {}
Will close this issue.
