### ISSUE TITLE
BatchNormalization layer fails to deserialize when working with Tensorflow

### ISSUE THREAD

**Issue by ladi-pomsar** [intel/openfl#422]
**Describe the bug**
When testing Tensorflow with more complex model, BatchNormalization layer fails to deserialize with error:
```
           ERROR    Collaborator failed with error: Unknown layer: BatchNormalization. Please ensure this object is passed to the `custom_objects`   envoy.py:75
                    argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.:
                    Traceback (most recent call last):
                      File "/home/openfl/venv/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 73, in run
                        self._run_collaborator()
                      File "/home/openfl/venv/lib/python3.8/site-packages/openfl/component/envoy/envoy.py", line 138, in _run_collaborator
                        col = plan.get_collaborator(self.name, self.root_certificate, self.private_key,
                      File "/home/openfl/venv/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 435, in get_collaborator
                        model_provider, task_keeper, data_loader = self.deserialize_interface_objects()
                      File "/home/openfl/venv/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 541, in <genexpr>
                        return (self.restore_object(api_layer['settings'][filename]) for filename in filenames)
                      File "/home/openfl/venv/lib/python3.8/site-packages/openfl/federated/plan/plan.py", line 561, in restore_object
                        obj = serializer_plugin.restore_object(filename)
                      File "/home/openfl/venv/lib/python3.8/site-packages/openfl/plugins/interface_serializer/cloudpickle_serializer.py", line 27,
                    in restore_object
                        return cloudpickle.load(f)
                      File "/home/openfl/venv/lib/python3.8/site-packages/openfl/plugins/frameworks_adapters/keras_adapter.py", line 24, in unpack
                        restored_model = deserialize(model)
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 123, in deserialize
                        return generic_utils.deserialize_keras_object(
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 674, in
                    deserialize_keras_object
                        deserialized_obj = cls.from_config(
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 667, in from_config
                        input_tensors, output_tensors, created_layers = reconstruct_from_config(
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1278, in
                    reconstruct_from_config
                        process_layer(layer_data)
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1260, in process_layer
                        layer = deserialize_layer(layer_data, custom_objects=custom_objects)
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 123, in deserialize
                        return generic_utils.deserialize_keras_object(
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 659, in
                    deserialize_keras_object
                        (cls, cls_config) = class_and_config_for_serialized_keras_object(
                      File "/home/openfl/venv/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 556, in
                    class_and_config_for_serialized_keras_object
                        raise ValueError(
                    ValueError: Unknown layer: BatchNormalization. Please ensure this object is passed to the `custom_objects` argument. See
                    https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
```

**To Reproduce**
Easiest way to reproduce is to edit the TF_MNIST example, steps are:
1. Change shape to '28, 28, 1' in mnist_shard_descriptor.py and delete the reshaping to 784 from download_data
2. Change shape in director config
3. Change network code to something like:
```def create_model():
    """Create keras model."""
      inputs = layers.Input((28, 28, 1))  
      conv_1 = layers.Conv2D(64, (3, 3),activation='relu')(inputs)  
      bn_1 = layers.BatchNormalization()(conv_1)  
      conv_2 = layers.Conv2D(64, (3, 3),activation='relu')(bn_1)  
      bn_2 = layers.BatchNormalization()(conv_2)  
      gap = layers.GlobalAveragePooling2D()(bn_2)  
      outputs = layers.Dense(10, name='predictions')(gap)  
      model = keras.Model(inputs=inputs, outputs=outputs)  
      return model
```
4. Observe the error on client while starting a collaborator service

**Expected behavior**
OpenFL should work with models implementing BN.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.0.2
 - Openfl version: 1.2.1
 - Tensorflow version: 2.8.0
 - Python version: 3.8.10
 - GPU: No

**Comment by mansishr** [comment]
Hi @ladi-pomsar, I reproduced the error with Tensorflow version 2.8. However, the issue is not seen for TF version 2.7 or lower. Could you run TF on 2.7?

**Comment by MasterSkepticista** [comment]
@mansishr 

Here's what I suspect is happening:
`tensorflow==2.8` is being installed in the notebook, which leads to instantiation of the `model` object (and subsequently `tf.keras.layers`) using this newer TF. But by the time serialization is reached, the envoy has already reverted to `tensorflow==2.7` by virtue of workspace and `requirements.txt` creation.

This mismatch of objects created between two versions may result in a serialization error. Expectedly, using TF2.7 will not raise the error, since both workspace and object comply with the versions.

**Comment by mansishr** [comment]
Thanks @MasterSkepticista for looking into it. I confirmed that `tensorflow==2.8` was indeed setup at the envoy side as well. I believe the issue is with this particular version of Tensorflow, not with OpenFL. A simple solution right now is to downgrade the TF version

**Comment by MasterSkepticista** [comment]
@mansishr 
Disabling `__reduce__` override on `tf.keras.Model` gets the experiment with `BatchNormalization` working on both TF2.7 and TF2.8
https://github.com/intel/openfl/blob/f4b28d710e2be31cdfa7487fdb4e8cb3a1387a5f/openfl/plugins/frameworks_adapters/keras_adapter.py#L45

`tf.keras.Model` supports pickle natively with the newer releases, which eliminates the need for the hotfix function we've added there.
Edit: Linking PR https://github.com/keras-team/keras/pull/14748 which later added native serialization capability. Our commits came earlier, safe to remove those methods from `keras_adapter.py`.

But either way, saving model via native APIs is recommended. 

Do we have any specific reasons to use pickle format for model (alternative: `model.save`)?

**Comment by ladi-pomsar** [comment]
> Hi @ladi-pomsar, I reproduced the error with Tensorflow version 2.8. However, the issue is not seen for TF version 2.7 or lower. Could you run TF on 2.7?

Hi @mansishr it is indeed true that we weren't able to reproduce it with lower versions.

Thank you @MasterSkepticista for looking into that.
