### ISSUE TITLE
Current protobuf==3.19.6 is not supported by TensorFlow 2.12

### ISSUE THREAD

**Issue by kminhta** [intel/openfl#831]
The current release for OpenFL requires `protobuf=3.19.6`
`TensorFlow 2.12` requires `protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3`

Because OpenFL will try to import TensorFlow if it is installed, importing OpenFL will result in an error:
```
[/usr/local/lib/python3.10/dist-packages/openfl/federated/task/__init__.py](https://localhost:8080/#) in <module>
     12     if pkgutil.find_loader('tensorflow'):
     13         # ignore deprecation warnings in command-line interface
---> 14         import tensorflow  # NOQA
     15 
     16 from .runner import TaskRunner  # NOQA

[/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py](https://localhost:8080/#) in <module>
     35 import typing as _typing
     36 
---> 37 from tensorflow.python.tools import module_util as _module_util
     38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     39 

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py](https://localhost:8080/#) in <module>
     35 
     36 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
---> 37 from tensorflow.python.eager import context
     38 
     39 # pylint: enable=wildcard-import

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/eager/context.py](https://localhost:8080/#) in <module>
     26 import numpy as np
     27 
---> 28 from tensorflow.core.framework import function_pb2
     29 from tensorflow.core.protobuf import config_pb2
     30 from tensorflow.core.protobuf import rewriter_config_pb2

[/usr/local/lib/python3.10/dist-packages/tensorflow/core/framework/function_pb2.py](https://localhost:8080/#) in <module>
      3 # source: tensorflow/core/framework/function.proto
      4 """Generated protocol buffer code."""
----> 5 from google.protobuf.internal import builder as _builder
      6 from google.protobuf import descriptor as _descriptor
      7 from google.protobuf import descriptor_pool as _descriptor_pool

ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/__init__.py)
```

This is problematic as Google Colab comes installed with TF 2.12 by default, causing a lot of our tutorials to break when run in colab. However, a user may downgrade it to TF 2.11 to workaround any issues as a quick fix, but it's worth investigating a more robust solution

**To Reproduce**
1. Install tensorflow==2.12
2. Install and import openfl

Alternatively
1. start a Google Colab notebook
2. install and import openfl

**Comment by sarthakpati** [comment]
Hi @psfoley @mansishr: this is an issue for GaNDLF integrations as well. All new PRs are erroring out with this message [[ref](https://github.com/mlcommons/GaNDLF/actions/runs/5730938894/job/15530760543?pr=693)]:

```python-traceback
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/bin/fx", line 33, in <module>
    sys.exit(load_entry_point('openfl', 'console_scripts', 'fx')())
  File "/opt/hostedtoolcache/Python/3.8.17/x64/bin/fx", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/__init__.py", line 6, in <module>
    from .interface.model import get_model
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/interface/model.py", line 14, in <module>
    from openfl.federated import Plan
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/federated/__init__.py", line 7, in <module>
    from .plan import Plan  # NOQA
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/federated/plan/__init__.py", line 6, in <module>
    from .plan import Plan
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/federated/plan/plan.py", line 17, in <module>
    from openfl.component.assigner.custom_assigner import Assigner
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/component/__init__.py", line 6, in <module>
    from .aggregator import Aggregator
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/component/aggregator/__init__.py", line 6, in <module>
    from .aggregator import Aggregator
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/component/aggregator/aggregator.py", line 19, in <module>
    from openfl.utilities.logs import write_metric
  File "/home/runner/work/GaNDLF/GaNDLF/openfl/openfl/utilities/logs.py", line 10, in <module>
    from tensorboardX import SummaryWriter
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorboardX/torchvis.py", line 10, in <module>
    from .writer import SummaryWriter
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorboardX/writer.py", line 16, in <module>
    from .comet_utils import CometLogger
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorboardX/comet_utils.py", line 7, in <module>
    from .summary import _clean_tag
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorboardX/summary.py", line 12, in <module>
    from .proto.summary_pb2 import Summary
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/tensorboardX/proto/summary_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/google/protobuf/internal/__init__.py)
```

Upon investigating, this is caused by a very old (read: **_ancient_**) version of protobuf [[ref](https://stackoverflow.com/a/72494013)], which is required by OpenFL and was introduced in June [[ref](https://github.com/securefederatedai/openfl/commit/fa71684e3b33c99ee7ec155d44c07b24231c2f9c)].

**Comment by JacobGlennAyers** [comment]
I tried upgrading to protobuf==3.20.3, though, I do get warnings that it is incompatible with openfl, but I have yet to encounter said problems when running the tutorials and such. I haven't played much with the business logic end of things. Any insights into why openfl was setup explicitly with version 3.19.6 in the setup.py script?
